from flask import Flask, render_template, redirect, url_for, request, flash , session
from flask_sqlalchemy import SQLAlchemy
import os
from flask_ckeditor import CKEditor
from werkzeug.utils import secure_filename
import smtplib
import random
from flask import jsonify






# ✅ Fix for Vercel (use /tmp if static/ is read-only)
if os.environ.get("VERCEL"):
    UPLOAD_FOLDER = "/tmp/uploads"
    db_path = "/tmp/my_database.db"
else:
    UPLOAD_FOLDER = "static/uploads"
    db_path = os.path.join(os.path.dirname(__file__), "my_database.db")

os.makedirs(UPLOAD_FOLDER, exist_ok=True)



app = Flask(__name__, static_folder="static",template_folder='templates')

# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg://go_todo_task_db_user:z3YSJb1og6V5aDVXuJqv9Kgsn7VgBpTO@dpg-d20liqndiees739m4op0-a.oregon-postgres.render.com/go_todo_task_db'


# if Render's connection string needs sslmode, you can append it:
# sql_url += "?sslmode=require"

# config (replace in your file)
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_URL
else:
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + db_path

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
ckeditor = CKEditor(app)
app.secret_key = 'your_secret_key'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# ✅ Ensure the upload folder exists (non-intrusive, does not change logic)
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

class PROJECT_POSTS(db.Model):
    __tablename__ = 'PROJECTS'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, unique=True)
    s_description = db.Column(db.String, nullable=False)
    img = db.Column(db.String, nullable=False)
    body = db.Column(db.String, nullable=False)
    
    def __repr__(self):
        return f"<PROJECT_POSTS id={self.id} title={self.title}desc={self.s_description}>"
    
    


    
@app.errorhandler(404)
def page_not_found(error):
    return render_template("error.html")

@app.route('/', methods=['GET', 'POST'])
def home_page():
    p = PROJECT_POSTS.query.all()
    print(p)
    if request.method == 'POST':
        name = request.form.get('name')
        subject = request.form.get('subject')
        phoneno = request.form.get('phoneno')
        email = request.form.get('email')
        msg = request.form.get('msg')
        print(name, email, phoneno, subject, msg)

        sender_mail = "maaz.irshad.siddiqui@gmail.com"
        password = "tvud sggg rdle ywll"
        message = f"""Subject: New Portfolio Contact Form Submission

Dear Admin,
You have received a new message via the contact form on your portfolio website.
Please find the details below:

------------------------------
Name     : {name}
Email    : {email}
Phone No : {phoneno}

Message:
{msg}
------------------------------

This message was automatically generated by your website's contact form.
Please respond to the sender at your earliest convenience.

Best regards,  
Portfolio Website Notification System
"""

        with smtplib.SMTP_SSL("smtp.gmail.com", port=465) as connection:
            connection.login(user=sender_mail, password=password)
            connection.sendmail(
                from_addr=sender_mail,
                to_addrs='siddiqui.maaz79@gmail.com',
                msg=message.encode("utf-8")
            )
        print("Mail Sent")
        flash(f'Your message has been successfully sent. Our team will review your details and get back to you shortly.','success')

    return render_template('index.html', all_post=p)

@app.route('/debug-posts')
def debug_posts():
    posts = PROJECT_POSTS.query.all()
    return jsonify([{
        "id": p.id,
        "title": p.title,
        "s_description": p.s_description,
        "img": p.img,
        "body": p.body
    } for p in posts])

USER_OTP = None
chars="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
URL_FOR_ADDING_PROJ = ''.join(random.choices(chars,k=12))
URL_FOR_DELETE_PROJ = ''.join(random.choices(chars,k=12))

@app.route('/make-changes', methods=['GET', 'POST'])
def make_changes():
    global USER_OTP
    global URL_FOR_ADDING_PROJ
    global URL_FOR_DELETE_PROJ
    
    if request.method == 'POST':
        OTP = request.form.get('otp', '').strip()
        option = request.form.get('course',"").strip()
        
        
        if not OTP:
            flash('No OTP found. Please request a new code.', 'warning')
            return render_template('validatepage.html')
        if not USER_OTP:
            flash('Request a code first','warning'); return render_template('validatepage.html')
        if not OTP.isdigit():
            flash('Enter numeric OTP','warning'); return render_template('validatepage.html')
        if int(OTP) == int(USER_OTP):
            # Testing Purpose
            # print("+________________________________+")
            # print(f"OTP:{OTP}\nUSER:{USER_OTP}")
            # print("+________________________________+")
            if int(option) == 1:
                return redirect(f'/{URL_FOR_ADDING_PROJ}')
            elif int(option) == 2:
                return redirect(f'/{URL_FOR_DELETE_PROJ}')
                
                
            else:
                flash('Password incorrect ','danger')
                return render_template('validatepage.html')
        else:
            flash('OTP incorrect.', 'danger')
            return render_template('validatepage.html')
    
    
    USER_OTP = str(random.randint(1000,9999))
    
    # ---------------------------------------

    sender_mail = "maaz.irshad.siddiqui@gmail.com"
    password = "tvud sggg rdle ywll"
    message = f"""Subject: Portfolio Verification Code

Dear Admin,

A verification request was initiated for your portfolio website.
Your 4-digit verification code is:

------------------------------
Verification Code: {USER_OTP}
------------------------------

This code was generated automatically to confirm activity on your portfolio.

Best regards,
Portfolio Website Notification System
"""

    with smtplib.SMTP_SSL("smtp.gmail.com", port=465) as connection:
        connection.login(user=sender_mail, password=password)
        connection.sendmail(
            from_addr=sender_mail,
            to_addrs='siddiqui.maaz79@gmail.com',
            msg=message.encode("utf-8")
        )
    print("Mail Sent")
    # ----------------------------------------
    
    flash('Mail sent check ','success')
    return render_template('validatepage.html')


                
    

@app.route(f'/{URL_FOR_ADDING_PROJ}', methods=['GET', 'POST'])
def add_new_project():


    if request.method == 'POST':
        print('+=========================================REACHED New project=========================================+')
        title = request.form.get('title')
        short_desc = request.form.get('short_desc')
        body = request.form.get('body')
        img_filename = ""

        img = request.files['image'] if 'image' in request.files else None
        

        if img and img.filename != '':
            filename = secure_filename(img.filename)
            img.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            img_filename = filename

        try:
            new_post = PROJECT_POSTS(
                title=title,
                s_description=short_desc,
                img=img_filename,
                body=body
            )
            print(title,img_filename,img,body)
            db.session.add(new_post)
            db.session.commit()
            flash('ADDED', 'success')
        except Exception as e:
            flash(f'ERROR: {e}', 'danger')
        return render_template('new_pro.html')

    
    return render_template('new_pro.html')



@app.route(f"/maaz-project/<id>")
def maaz_project(id):

    print('+=========================================REACHED View Project=========================================+')
    post = PROJECT_POSTS.query.filter_by(id=int(id)).first()
    return render_template("specific-project.html", post=post)
# all_post

@app.route(f"/{URL_FOR_DELETE_PROJ}")
def maaz_project_edit():
    
    post = PROJECT_POSTS.query.all()
    return render_template("delete.html", post=post)

@app.route("/delete-maaz-project/<id>", methods=["POST","GET"])
def delete_maaz_project(id):
    post = PROJECT_POSTS.query.filter_by(id=int(id)).first()
    db.session.delete(post)
    db.session.commit()
    
    post = PROJECT_POSTS.query.all()
    return render_template("delete.html", post=post)

with app.app_context():
    db.create_all()

    

if __name__ == '__main__':
    app.run(port=5000, debug=True)
